import { CRM_DASHBOARD_COPY } from "@/lib/crmDashboardCopy";

export const CRM_ATTENDANCE_COPY = {
  navDashboard: "К дашборду",
  heroEyebrow: "Посещаемость",
  heroTitle: "Посещаемость",
  heroSubtitle: "Оперативный контур посещаемости по командам и месяцам: лидеры, пропуски и зоны риска.",
  loadingTitle: "Загружаем посещаемость",
  loadingHint: "Команды, тренировки и статистика по присутствию.",
  errorTitle: "Не удалось загрузить посещаемость",
  errorHint: CRM_DASHBOARD_COPY.errorHint,
  retryCta: CRM_DASHBOARD_COPY.retryCta,
  filtersKicker: "Фильтры",
  filtersTitle: "Отбор данных",
  filtersHint: "Команда и период обновляют выбранный блок аналитики.",
  allTeams: "Все команды",
  yearsKicker: "Период",
  yearsTitle: "Год",
  tabsKicker: "Раздел",
  tabsTitle: "Операционный срез",
  tabPlayers: "Игроки",
  tabAttendance: "Посещаемость",
  tabFinance: "Финансы",
  tabCoaches: "Тренеры",
  summaryKicker: "Сводка",
  summaryTitle: "Текущая посещаемость",
  summaryHint: "Быстрый ответ: кто ходит стабильно и где есть провалы.",
  statAvgRate: "Средняя посещаемость",
  statBestTeam: "Лучшая команда",
  statAbsences: "Всего пропусков",
  statTopPlayer: "Лидер посещаемости",
  sectionTeamsKicker: "Распределение",
  sectionTeamsTitle: "Посещаемость по командам",
  sectionTeamsHint: "Процент присутствия по каждой команде.",
  sectionMonthKicker: "Динамика",
  sectionMonthTitle: "Посещаемость по месяцам",
  sectionMonthHint: "Тренд посещаемости за год по выбранным фильтрам.",
  sectionTopKicker: "Лидеры",
  sectionTopTitle: "Топ по посещаемости",
  sectionTopHint: "Игроки с лучшим процентом присутствия.",
  sectionAbsencesKicker: "Риски",
  sectionAbsencesTitle: "Больше всего пропусков",
  sectionAbsencesHint: "Игроки, требующие внимания тренера.",
  emptyTitle: "Нет данных для отображения",
  emptyHint: "Смените фильтры или дождитесь накопления посещаемости.",
} as const;
