import { CRM_DASHBOARD_COPY } from "@/lib/crmDashboardCopy";

export const CRM_ACTIONS_COPY = {
  navDashboard: "К дашборду",
  heroEyebrow: "Follow-up",
  heroTitle: "Сообщения с родителями",
  heroSubtitle: "Операционный контур follow-up: быстрый вход в диалоги, недавние обновления и контекст по игрокам.",
  loadingTitle: "Загружаем follow-up ленту",
  loadingHint: "Список диалогов, последние сообщения и фильтры.",
  errorTitle: "Не удалось загрузить диалоги",
  errorHint: CRM_DASHBOARD_COPY.errorHint,
  retryCta: CRM_DASHBOARD_COPY.retryCta,
  filtersKicker: "Фильтры",
  filtersTitle: "Поиск диалогов",
  filtersHint: "Ищите по игроку или родителю, чтобы быстро открыть нужный тред.",
  searchPlaceholder: "Поиск по игроку или родителю...",
  summaryKicker: "Сводка",
  summaryTitle: "Текущий контур",
  summaryHint: "Показывает объем диалогов и свежие обновления.",
  statTotal: "Всего диалогов",
  statRecent: "Обновлено за 24 ч",
  statWithMessages: "С сообщениями",
  statWithoutMessages: "Без сообщений",
  listKicker: "Список",
  listTitle: "Диалоги",
  listHint: "Главный путь: откройте диалог и продолжите follow-up.",
  emptyTitle: "Диалогов пока нет",
  emptyHint: "Родители создают диалоги из приложения, после этого они появятся в CRM.",
  emptyFilteredTitle: "Ничего не найдено",
  emptyFilteredHint: "Сбросьте фильтр или уточните имя игрока/родителя.",
} as const;
