import { CRM_DASHBOARD_COPY } from "@/lib/crmDashboardCopy";

export const CRM_COMMUNICATIONS_DETAIL_COPY = {
  navCommunications: "К коммуникациям",
  navDashboard: "К дашборду",
  heroEyebrow: "Диалог",
  heroTitleFallback: "Диалог с родителем",
  heroSubtitle: "Контекст общения по игроку, история сообщений и быстрый ответ в одном экране.",
  loadingTitle: "Загружаем диалог",
  loadingHint: "Участники, лента сообщений и мета активности.",
  errorTitle: "Не удалось загрузить диалог",
  errorHint: CRM_DASHBOARD_COPY.errorHint,
  retryCta: CRM_DASHBOARD_COPY.retryCta,
  notFoundTitle: "Диалог не найден",
  notFoundHint: "Проверьте ссылку или вернитесь к списку коммуникаций.",
  summaryKicker: "Сводка",
  summaryTitle: "Контекст диалога",
  summaryHint: "Кто участвует, когда был последний контакт и есть ли непрочитанные сообщения.",
  statParticipants: "Участники",
  statPlayer: "Игрок",
  statLastMessage: "Последняя активность",
  statUnread: "Непрочитанные",
  threadKicker: "Тред",
  threadTitle: "История сообщений",
  threadHint: "Основной поток коммуникации по игроку.",
  composerKicker: "Ответ",
  composerTitle: "Новое сообщение",
  composerHint: "Отправка ответа родителю в текущем диалоге.",
  emptyThread: "Сообщений пока нет",
  inputPlaceholder: "Введите сообщение...",
  sendCta: "Отправить",
  coachLabel: "Тренер",
  parentLabel: "Родитель",
} as const;
