/**
 * Copy for CRM dashboard (`(dashboard)/dashboard/page`). No business logic.
 */

export const CRM_DASHBOARD_COPY = {
  heroEyebrow: "Дашборд",
  heroSubtitle:
    "Команды, игроки, тренировки и расписание — быстрые ссылки ниже; здесь сводка, ближайшие слоты и журнал.",
  heroGreetingFallback: "Администратор",
  hubNavSchedule: "Расписание",
  hubNavTrainings: "Тренировки",
  hubNavTeams: "Команды",
  hubNavPlayers: "Игроки",
  roleChipLabel: "Роль",
  loadingTitle: "Загружаем обзор",
  loadingHint: "Сводка, расписание и журнал активности.",
  errorTitle: "Не удалось загрузить данные",
  errorHint: "Проверьте соединение и повторите попытку.",
  errorRecoverHint: "Разделы CRM недоступны, пока обзор не загрузится.",
  retryCta: "Повторить",
  statsKicker: "Сводка",
  statsTitle: "Ключевые показатели",
  statsHint: "Блоки с доступом ведут в соответствующие разделы.",
  statPlayers: "Игроки",
  statTeams: "Команды",
  statCoaches: "Тренеры",
  statTrainingsMonth: "Тренировки",
  statTrainingsMonthSuffix: " / мес.",
  statAttendance: "Посещаемость",
  statPaid: "Оплачено",
  statDebt: "Задолженность",
  statRecs: "Рекомендации",
  currencySuffix: " ₽",
  sectionTrainingsKicker: "Расписание",
  sectionTrainingsTitle: "Ближайшие тренировки",
  sectionTrainingsHint: "Переход к карточке тренировки в CRM.",
  sectionTrainingsLink: "Всё расписание",
  sectionTrainingsEmpty: "Ближайших тренировок нет",
  sectionTrainingsEmptyHint: "Создайте слот в расписании или откройте календарь команд.",
  sectionActivityKicker: "Журнал",
  sectionActivityTitle: "Последние действия",
  sectionActivityHint: "События по школе за последнее время.",
  sectionActivityLink: "Аналитика",
  sectionActivityEmpty: "Пока нет активности",
  sectionActivityEmptyHint: "События появятся после работы с игроками, командами и финансами.",
  sectionFinanceKicker: "Финансы",
  sectionFinanceTitle: "Сводка по оплатам",
  sectionFinanceHint: "Данные за текущий период в сводке API.",
  sectionFinancePaid: "Оплачено за месяц",
  sectionFinanceDebt: "Задолженность",
  sectionFinanceShare: "Доля оплат",
  sectionFinanceCta: "Перейти в финансы",
  sectionRecsKicker: "Развитие",
  sectionRecsTitle: "Рекомендации тренеров",
  sectionRecsHint: "Счётчик за месяц по данным сводки.",
  sectionRecsSubtitle: "рекомендаций в этом месяце",
  sectionRecsCta: "Подробнее",
  quickActionsKicker: "Действия",
  quickActionsTitle: "Быстрые действия",
  quickActionsHint: "Создание и переходы с учётом прав роли.",
  quickActionsEmpty: "Нет доступных быстрых действий для вашей роли.",
} as const;
