import { CRM_DASHBOARD_COPY } from "@/lib/crmDashboardCopy";

export const CRM_FINANCE_DETAIL_COPY = {
  backFinance: "К финансам",
  backDashboard: "К дашборду",
  heroEyebrow: "Финансовая запись",
  heroTitle: "Платеж",
  heroSubtitle: "Детали начисления, статус оплаты и связанные данные игрока.",
  loadingTitle: "Загружаем финансовую запись",
  loadingHint: "Информация по игроку, периоду и статусу оплаты.",
  errorTitle: "Не удалось загрузить платеж",
  errorHint: CRM_DASHBOARD_COPY.errorHint,
  retryCta: CRM_DASHBOARD_COPY.retryCta,
  notFoundTitle: "Запись не найдена",
  notFoundHint: "Проверьте ссылку или вернитесь к списку финансовых записей.",
  notFoundBack: "К списку финансов",
  notFoundDashboard: "На дашборд",
  sectionMainKicker: "Основное",
  sectionMainTitle: "Информация по записи",
  sectionMainHint: "Кто, за какой период и в каком статусе находится платеж.",
  sectionEditKicker: "Действия",
  sectionEditTitle: "Редактирование записи",
  sectionEditHint: "Обновляйте сумму, статус и комментарий без смены контракта API.",
  sectionHistoryKicker: "История",
  sectionHistoryTitle: "Таймлайн изменений",
  sectionHistoryHint: "Служебные отметки по созданию и последнему обновлению.",
  fieldPlayer: "Игрок",
  fieldTeam: "Команда",
  fieldPeriod: "Период",
  fieldAmount: "Сумма",
  fieldStatus: "Статус",
  fieldPaidAt: "Дата оплаты",
  fieldComment: "Комментарий",
  fieldCreatedAt: "Создан",
  fieldUpdatedAt: "Обновлен",
  saveCta: "Сохранить",
  savingCta: "Сохранение...",
  statusPaid: "Оплачено",
  statusUnpaid: "Не оплачено",
  statusPartial: "Частично",
  statusOverdue: "Просрочено",
} as const;
