import { CRM_DASHBOARD_COPY } from "@/lib/crmDashboardCopy";

export const CRM_FINANCE_COPY = {
  navDashboard: "К дашборду",
  heroEyebrow: "Финансы",
  heroTitle: "Финансы и оплаты",
  heroSubtitle: "Контроль оплат по игрокам и командам: сводка, должники, история и начисления.",
  bulkCta: "Массовое начисление",
  newPaymentCta: "Новый платеж",
  loadingTitle: "Загружаем финансовый контур",
  loadingHint: "Сводка, платежи, команды и список должников.",
  errorTitle: "Не удалось загрузить финансовые данные",
  errorHint: CRM_DASHBOARD_COPY.errorHint,
  retryCta: CRM_DASHBOARD_COPY.retryCta,
  emptyTitle: "Платежей пока нет",
  emptyHint: "Создайте первый платеж или выполните массовое начисление.",
  filtersKicker: "Фильтры",
  filtersTitle: "Поиск и отбор",
  filtersHint: "Измените параметры и примените выборку.",
  filterSearch: "Игрок...",
  filterTeamAll: "Все команды",
  filterStatusAll: "Все статусы",
  filterMonthAll: "Все месяцы",
  applyFilters: "Применить",
  sectionSummaryKicker: "Сводка",
  sectionSummaryTitle: "Текущий месяц",
  sectionSummaryHint: "Показывает общий сбор, просрочку и статус счетов.",
  kpiCollected: "Собрано за месяц",
  kpiUnpaid: "Не оплачено",
  kpiDebt: "Задолженность",
  kpiPaidCount: "Оплачено счетов",
  sectionChartKicker: "Динамика",
  sectionChartTitle: "Оплаты по месяцам",
  sectionChartHint: "Сравнение оплаченных сумм по месяцам выбранного года.",
  sectionTableKicker: "Реестр",
  sectionTableTitle: "Таблица оплат",
  sectionTableHint: "Быстрое чтение: кто, команда, месяц, сумма и статус.",
  colPlayer: "Игрок",
  colTeam: "Команда",
  colMonth: "Месяц",
  colAmount: "Сумма",
  colStatus: "Статус",
  colPaidAt: "Дата оплаты",
  colComment: "Комментарий",
  colActions: "Действия",
  openCta: "Открыть",
  sectionLastKicker: "Лента",
  sectionLastTitle: "Последние платежи",
  sectionUpcomingKicker: "Контроль",
  sectionUpcomingTitle: "Ближайшие неоплаченные",
  sectionTeamsKicker: "Сравнение",
  sectionTeamsTitle: "По командам",
  sectionTeamsChartTitle: "График по командам",
  sectionDebtorsKicker: "Риск",
  sectionDebtorsTitle: "Топ должников",
  debtorsEmpty: "Должников нет",
  bulkTitle: "Массовое начисление",
  bulkTeam: "Команда",
  bulkMonth: "Месяц",
  bulkYear: "Год",
  bulkAmount: "Сумма (₽)",
  bulkSubmit: "Создать для всех игроков",
  statusPaid: "Оплачено",
  statusUnpaid: "Не оплачено",
  statusPartial: "Частично",
  statusOverdue: "Просрочено",
  monthSuffix: " мес.",
} as const;
