import { CRM_DASHBOARD_COPY } from "@/lib/crmDashboardCopy";

export const CRM_MARKETPLACE_COPY = {
  hubNavDashboard: "К дашборду",
  hubEyebrow: "Marketplace",
  hubTitle: "Маркетплейс тренеров",
  hubSubtitle: "Центр управления профилями тренеров, публикацией услуг и заявками родителей.",
  hubLoadingTitle: "Загружаем marketplace hub",
  hubLoadingHint: "Профили тренеров, услуги и pipeline заявок.",
  hubErrorTitle: "Не удалось загрузить marketplace",
  hubErrorHint: CRM_DASHBOARD_COPY.errorHint,
  hubRetryCta: CRM_DASHBOARD_COPY.retryCta,
  hubSummaryKicker: "Сводка",
  hubSummaryTitle: "Текущее состояние",
  hubSummaryHint: "Показывает объём активов и входящий спрос по заявкам.",
  hubStatCoaches: "Тренеров",
  hubStatPublished: "Опубликовано",
  hubStatDrafts: "Черновики",
  hubStatServices: "Услуг",
  hubPipelineKicker: "Pipeline",
  hubPipelineTitle: "Заявки и статусы",
  hubPipelineHint: "Быстрый срез по этапам бронирования.",
  hubStatReqTotal: "Всего заявок",
  hubStatReqNew: "Новые",
  hubStatReqInProgress: "В работе",
  hubStatReqResolved: "Закрытые",
  hubListKicker: "Каталог",
  hubListTitle: "Тренеры маркетплейса",
  hubListHint: "Открывайте профиль тренера для управления карточкой и услугами.",
  hubFiltersKicker: "Фильтры",
  hubFiltersTitle: "Поиск и отбор",
  hubFiltersHint: "Ищите тренера по имени и фильтруйте по статусу публикации.",
  hubSearchPlaceholder: "Поиск по имени тренера...",
  hubStatusAll: "Все статусы",
  hubStatusPublished: "Только опубликованные",
  hubStatusDraft: "Только черновики",
  hubEmptyFilteredTitle: "Тренеры не найдены",
  hubEmptyFilteredHint: "Сбросьте фильтры или измените поисковый запрос.",
  hubEmptyTitle: "Тренеров в маркетплейсе пока нет",
  hubEmptyHint: "Добавьте первого тренера или импортируйте данные seed.",
  hubRequestsCta: "Открыть заявки",
  hubAddCoachCta: "Добавить тренера",
  hubEditCoachCta: "Открыть профиль",
  hubColCoach: "Тренер",
  hubColCity: "Город",
  hubColSpecialties: "Специализации",
  hubColOffer: "Опыт / Цена",
  hubColStatus: "Статус",
  hubColActions: "Действия",
  hubPublishedLabel: "Опубликован",
  hubDraftLabel: "Черновик",
  hubNoSpecialty: "Без специализации",
  hubNoCity: "—",
  navDashboard: "К дашборду",
  navMarketplace: "К маркетплейсу",
  heroEyebrow: "Marketplace",
  heroTitle: "Заявки на занятия",
  heroSubtitle: "Входящие бронирования от родителей: обработка статусов, быстрый контакт и следующий action.",
  loadingTitle: "Загружаем заявки",
  loadingHint: "Статусы, контакты родителей и данные по тренерам.",
  errorTitle: "Не удалось загрузить заявки",
  errorHint: CRM_DASHBOARD_COPY.errorHint,
  retryCta: CRM_DASHBOARD_COPY.retryCta,
  filtersKicker: "Фильтры",
  filtersTitle: "Статусы заявок",
  filtersHint: "Отберите заявки по этапу обработки.",
  allStatuses: "Все статусы",
  summaryKicker: "Сводка",
  summaryTitle: "Текущий pipeline",
  summaryHint: "Показывает объём заявок и что требует внимания прямо сейчас.",
  statTotal: "Всего заявок",
  statNew: "Новые",
  statInProgress: "В работе",
  statResolved: "Закрытые",
  listKicker: "Реестр",
  listTitle: "Список заявок",
  listHint: "Основной путь: контакт, контекст, статус и действие по заявке.",
  emptyTitle: "Заявок пока нет",
  emptyHint: "Новые заявки от родителей появятся здесь.",
  emptyFilteredTitle: "Нет заявок по фильтру",
  emptyFilteredHint: "Сбросьте статус или выберите другой этап.",
  coachPrefix: "Тренер",
  preferredDatePrefix: "Желаемая дата",
  statusNew: "Новая",
  statusInProgress: "В работе",
  statusConfirmed: "Подтверждена",
  statusDeclined: "Отклонена",
  toWorkCta: "В работу",
  confirmCta: "Подтвердить",
  declineCta: "Отклонить",
} as const;
