import { CRM_DASHBOARD_COPY } from "@/lib/crmDashboardCopy";

export const CRM_MARKETPLACE_COACH_DETAIL_COPY = {
  navMarketplace: "К маркетплейсу",
  navRequests: "К заявкам",
  navDashboard: "К дашборду",
  heroEyebrow: "Marketplace coach",
  heroTitle: "Профиль тренера",
  heroSubtitle: "Управление карточкой тренера: публикация, форматы занятий, специализации и коммерческие параметры.",
  loadingTitle: "Загружаем профиль тренера",
  loadingHint: "Основные данные, форматы и статус публикации.",
  errorTitle: "Не удалось загрузить профиль",
  errorHint: CRM_DASHBOARD_COPY.errorHint,
  retryCta: CRM_DASHBOARD_COPY.retryCta,
  notFoundTitle: "Тренер не найден",
  notFoundHint: "Проверьте ссылку или вернитесь к списку тренеров в маркетплейсе.",
  sectionSummaryKicker: "Сводка",
  sectionSummaryTitle: "Операционный срез",
  sectionSummaryHint: "Ключевые параметры карточки для быстрого контроля перед публикацией.",
  statCity: "Город",
  statStatus: "Статус",
  statSpecialties: "Специализаций",
  statFormats: "Форматов",
  sectionMainKicker: "Профиль",
  sectionMainTitle: "Основная информация",
  sectionMainHint: "Имя, город и описание тренера, которые видят родители.",
  sectionExpertiseKicker: "Услуги",
  sectionExpertiseTitle: "Специализации и форматы",
  sectionExpertiseHint: "Определяет, как карточка тренера отображается в поиске.",
  sectionCommerceKicker: "Коммерция",
  sectionCommerceTitle: "Опыт, цена и рейтинг",
  sectionCommerceHint: "Быстрая проверка коммерческих атрибутов профиля.",
  sectionPublishKicker: "Публикация",
  sectionPublishTitle: "Статус видимости",
  sectionPublishHint: "Управляет доступностью тренера в приложении родителей.",
  saveCta: "Сохранить",
  savingCta: "Сохранение...",
  cancelCta: "Отмена",
  published: "Опубликован",
  draft: "Черновик",
  loadErrorDefault: "Ошибка загрузки",
  saveErrorDefault: "Ошибка сохранения",
} as const;
