import { CRM_DASHBOARD_COPY } from "@/lib/crmDashboardCopy";

export const CRM_REPORTS_COPY = {
  navDashboard: "К дашборду",
  heroEyebrow: "Отчеты",
  heroTitle: "Рейтинг игроков",
  heroSubtitle: "Оперативный срез по форме игроков: фильтруйте, сканируйте таблицу и открывайте карточку за один шаг.",
  loadingTitle: "Загружаем отчеты",
  loadingHint: "Рейтинг, фильтры и сводка по состоянию игроков.",
  errorTitle: "Не удалось загрузить рейтинг",
  errorHint: CRM_DASHBOARD_COPY.errorHint,
  retryCta: CRM_DASHBOARD_COPY.retryCta,
  filtersKicker: "Фильтры",
  filtersTitle: "Отбор выборки",
  filtersHint: "Команда, позиция и год рождения обновляют таблицу автоматически.",
  allTeams: "Все команды",
  allPositions: "Все позиции",
  allBirthYears: "Все года рождения",
  summaryKicker: "Сводка",
  summaryTitle: "Текущее состояние",
  summaryHint: "Помогает быстро понять объем и уровень лидеров в выборке.",
  statInRating: "Игроков в рейтинге",
  statTop1: "Лидер",
  statTop10: "Топ-10 порог",
  statAvg: "Средний рейтинг",
  tableKicker: "Реестр",
  tableTitle: "Таблица рейтинга",
  tableHint: "Основной путь чтения: место, имя, команда, возраст, позиция, рейтинг.",
  emptyTitle: "Нет данных для отображения",
  emptyHint: "Смените фильтры или дождитесь заполнения показателей игрока.",
  colRank: "Место",
  colName: "Имя",
  colTeam: "Команда",
  colAge: "Возраст",
  colPosition: "Позиция",
  colRating: "Рейтинг",
} as const;
