/**
 * Copy for CRM new training form (`(dashboard)/trainings/new/page`). No business logic.
 */

import { CRM_DASHBOARD_COPY } from "@/lib/crmDashboardCopy";

export const CRM_TRAINING_CREATE_COPY = {
  heroEyebrow: "Создание",
  heroTitle: "Новая тренировка",
  heroSubtitle:
    "Привяжите к команде, задайте время и место. Один слот или серия по дням недели — после сохранения откроется карточка или расписание.",
  backTrainings: "К списку тренировок",
  backSchedule: "К расписанию",
  teamsLoadingTitle: "Загружаем команды",
  teamsLoadingHint: "Без команды тренировку не сохранить.",
  teamsErrorTitle: "Не удалось загрузить команды",
  teamsErrorHint: CRM_DASHBOARD_COPY.errorHint,
  retryCta: CRM_DASHBOARD_COPY.retryCta,
  emptyTeamsTitle: "Нет команд для выбора",
  emptyTeamsHint: "Сначала добавьте команду школы — затем вернитесь сюда.",
  emptyTeamsCta: "К командам",
  sectionMainKicker: "Основное",
  sectionMainTitle: "Команда и название",
  sectionMainHint: "Команда и название обязательны.",
  sectionTimeKicker: "Время",
  sectionTimeTitle: "Дата, старт и длительность",
  sectionTimeHint: "Для серии задаётся дата начала и повтор по дням недели.",
  sectionDetailsKicker: "Детали",
  sectionDetailsTitle: "Место и заметки",
  sectionDetailsHint: "По желанию — уточните площадку и контекст для тренеров.",
  labelTeam: "Команда",
  labelTitle: "Название",
  recurringLabel: "Регулярное расписание (серия)",
  recurringHelper: "Несколько слотов по выбранным дням; по окончании — переход в расписание.",
  labelDate: "Дата",
  labelDateRecurring: "Дата начала",
  labelTime: "Время начала",
  labelDuration: "Длительность, мин",
  labelWeekdays: "Дни недели",
  labelWeeks: "Недель в серии",
  labelLocation: "Место",
  labelNotes: "Заметки",
  optional: "необязательно",
  placeholderTitle: "Например: лёд U12",
  placeholderLocation: "Ледовая арена, зал…",
  placeholderNotes: "Фокус тренировки, заметки…",
  selectTeamPlaceholder: "Выберите команду",
  footerHintSingle: "После сохранения откроется карточка тренировки.",
  footerHintRecurring: "После создания серии откроется расписание.",
  submitSingle: "Сохранить тренировку",
  submitRecurring: "Создать серию",
  submitting: "Сохранение…",
  cancel: "Отмена",
} as const;
