/**
 * Тексты экрана управления объявлениями команды (CRM).
 */

export const CRM_TEAM_ANNOUNCEMENTS_COPY = {
  pageTitle: "Объявления команды",
  pageSubtitle:
    "Родители увидят это в приложении в канале «Объявления команды». Это не чат и не общая переписка.",
  backToTeam: "К карточке команды",
  loading: "Загружаем объявления…",
  loadErrorTitle: "Не удалось загрузить список",
  loadErrorHint: "Проверьте подключение и попробуйте снова.",
  retry: "Повторить",
  emptyTitle: "Пока нет объявлений",
  emptyHint: "Создайте первое — родители получат новость в своём приложении после публикации.",
  newCta: "Новое объявление",
  cancel: "Отмена",
  saveCreate: "Опубликовать",
  saveDraft: "Сохранить как черновик",
  saveEdit: "Сохранить",
  kindLabel: "Тип",
  titleLabel: "Заголовок",
  bodyLabel: "Текст",
  pinLabel: "Закрепить вверху списка",
  publishLabel: "Показать родителям",
  unpublishLabel: "Снять с публикации",
  publishHelp: "Пока снято, родители не видят объявление в приложении.",
  editTitle: "Редактирование",
  createTitle: "Новое объявление",
  validationTitle: "Введите заголовок",
  validationBody: "Введите текст",
  saved: "Сохранено",
  pinCta: "Закрепить",
  unpinCta: "Открепить",
  publishCta: "Опубликовать",
  deleteCta: "Удалить",
  confirmDelete: "Удалить объявление безвозвратно?",
  statusPublished: "На канале",
  statusDraft: "Черновик",
  statusHidden: "Снято с публикации",
  authorLine: "Автор",
  kinds: {
    general: "Общее объявление",
    schedule_change: "Изменение расписания",
    game_day: "День игры",
    important: "Важное",
  } as const,
  legacyKindFallback: "Объявление",
} as const;
