/**
 * Copy for CRM team card (`(dashboard)/teams/[id]/page`). No business logic.
 */

import { CRM_DASHBOARD_COPY } from "@/lib/crmDashboardCopy";

export const CRM_TEAM_DETAIL_COPY = {
  heroEyebrow: "Карточка команды",
  heroSubtitle: "Состав, слоты и посещаемость — дальше карточки игроков и тренировок.",
  loadingTitle: "Загружаем команду",
  loadingHint: "Состав, тренировки и сводные показатели.",
  errorTitle: "Не удалось загрузить команду",
  errorHint: CRM_DASHBOARD_COPY.errorHint,
  retryCta: CRM_DASHBOARD_COPY.retryCta,
  notFoundTitle: "Команда не найдена",
  notFoundHint: "Проверьте ссылку или вернитесь к списку школы.",
  backToList: "К списку команд",
  backShort: "Назад к командам",
  backSchedule: "К расписанию",
  notFoundScheduleCta: "К расписанию",
  editCta: "Редактировать",
  scheduleCta: "Расписание MVP",
  groupsCta: "Группы",
  assignmentsCta: "Распределение",
  addTrainingCta: "Тренировка",
  deleteCta: "Удалить",
  confirmDelete: "Удалить команду?",
  schoolFallback: "Школа не указана",
  rosterKicker: "Состав",
  rosterTitle: "Состав команды",
  rosterHint: "Переход в карточку игрока — посещаемость и оценки на тренировках.",
  statsKicker: "Показатели",
  statsTitle: "Командная статистика",
  statsHint: "Сводка по составу и последним тренировкам в CRM.",
  scheduleKicker: "Календарь",
  scheduleTitle: "Расписание команды",
  scheduleHint: "До 15 ближайших записей — полный журнал в карточке тренировки.",
  attendanceKicker: "Дисциплина",
  attendanceTitle: "Посещаемость по тренировкам",
  attendanceHint: "Краткая сводка по последним тренировкам.",
  emptyRoster: "Игроков в составе пока нет",
  emptySchedule: "Тренировок по команде нет",
  emptyAttendance: "Нет данных о посещаемости",
  statPlayers: "Игроков",
  statAttendance: "Посещаемость",
  statTrainingsMonth: "Тренировок в месяце",
  statTrainingsTotal: "Всего тренировок",
  tableTraining: "Тренировка",
  tableDate: "Дата",
  tablePresent: "Присутствовало",
  absentLabel: "отсутствовало",
} as const;
