import { CRM_DASHBOARD_COPY } from "@/lib/crmDashboardCopy";

export const CRM_TEAM_SCHEDULE_COPY = {
  navBackTeam: "К команде",
  navBackSchedule: "К расписанию",
  heroEyebrow: "Командное расписание",
  heroTitle: "План тренировок команды",
  heroSubtitle: "Неделя по команде: ближайшие слоты, типы тренировок и быстрые переходы к управлению.",
  groupsCta: "Группы",
  assignmentsCta: "Распределение",
  addTrainingCta: "Добавить тренировку",
  loadingTitle: "Загружаем расписание команды",
  loadingHint: "Слоты недели и привязанные группы.",
  errorTitle: "Не удалось загрузить расписание",
  errorHint: CRM_DASHBOARD_COPY.errorHint,
  retryCta: CRM_DASHBOARD_COPY.retryCta,
  invalidTeamTitle: "Некорректная команда",
  invalidTeamHint: "Проверьте ссылку или вернитесь к списку команд.",
  invalidTeamBack: "К командам",
  weekRangeLabel: "Неделя",
  summaryKicker: "Сводка",
  summaryTitle: "Операционный срез",
  summaryHint: "Показывает общий объем слотов и ближайшую тренировку.",
  summaryTotal: "Тренировок в неделе",
  summaryNext: "Ближайшая тренировка",
  summaryTypes: "Типы активностей",
  summaryGroups: "Группы в расписании",
  sectionKicker: "Расписание",
  sectionTitle: "Слоты по дням",
  sectionHint: "Основной слой планирования: день, время, тип, группа и локация.",
  dayEmpty: "Нет тренировок",
  weekEmptyTitle: "На эту неделю слотов нет",
  weekEmptyHint: "Создайте тренировку или проверьте привязку группы к команде.",
  createTitle: "Новая тренировка",
  deleteConfirm: "Удалить тренировку из расписания?",
} as const;
