import type { CoachReview } from "@/types/review";

export const MOCK_COACH_REVIEWS: CoachReview[] = [
  {
    id: "r1",
    coachId: "c1",
    parentName: "Анна К.",
    playerAge: 12,
    playerPosition: "нападающий",
    rating: 5.0,
    date: "2025-03-01",
    title: "Сильный прогресс по катанию",
    text: "После 6 тренировок у сына заметно улучшился первый шаг и устойчивость. Очень понятная подача, хорошая обратная связь.",
    tags: ["Катание", "Баланс", "Скорость"],
    improvementArea: "Катание",
    verifiedBooking: true,
  },
  {
    id: "r2",
    coachId: "c2",
    parentName: "Дмитрий С.",
    playerAge: 11,
    rating: 4.8,
    date: "2025-02-28",
    title: "Отлично работает над броском",
    text: "Понравилась структура тренировки и конкретные упражнения, которые можно повторять самостоятельно.",
    tags: ["Бросок", "Техника"],
    improvementArea: "Бросок",
    verifiedBooking: true,
  },
  {
    id: "r3",
    coachId: "c1",
    parentName: "Елена В.",
    playerAge: 13,
    playerPosition: "защитник",
    rating: 5.0,
    date: "2025-02-25",
    title: "Ребёнок стал увереннее в борьбе",
    text: "Хорошо объясняет, умеет работать с детьми, чувствуется опыт.",
    tags: ["Физика", "Подход к детям"],
    verifiedBooking: true,
  },
  {
    id: "r4",
    coachId: "c2",
    parentName: "Михаил П.",
    playerAge: 12,
    playerPosition: "нападающий",
    rating: 5.0,
    date: "2025-02-20",
    title: "Заметный прогресс по щелчку",
    text: "За 4 занятия сын стал бить гораздо точнее. Рекомендую всем, кто хочет улучшить бросок.",
    tags: ["Бросок", "Скорость"],
    improvementArea: "Бросок",
    verifiedBooking: true,
  },
  {
    id: "r5",
    coachId: "c5",
    parentName: "Сергей А.",
    playerAge: 12,
    rating: 4.9,
    date: "2025-02-18",
    title: "Улучшили силовую борьбу",
    text: "Сын перестал терять шайбу в углах. Силовой блок стал увереннее. Хорошая программа.",
    tags: ["Физика", "Силовая борьба"],
    improvementArea: "Силовая борьба",
    verifiedBooking: true,
  },
  {
    id: "r6",
    coachId: "c4",
    parentName: "Ольга М.",
    playerAge: 11,
    rating: 4.7,
    date: "2025-02-15",
    title: "Техника владения шайбой",
    text: "Хорошо ставит технику ведения. Ребёнок стал увереннее в игре у борта.",
    tags: ["Stickhandling", "Игра у борта"],
    improvementArea: "Игра у борта",
    verifiedBooking: true,
  },
  {
    id: "r7",
    coachId: "c3",
    parentName: "Андрей К.",
    playerAge: 12,
    rating: 5.0,
    date: "2025-02-12",
    title: "Топовый тренер",
    text: "Высочайший уровень. Сын значительно вырос в игровом мышлении.",
    tags: ["Подкатка", "Игровое мышление"],
    verifiedBooking: true,
  },
  {
    id: "r8",
    coachId: "c6",
    parentName: "Ирина Т.",
    playerAge: 13,
    playerPosition: "нападающий",
    rating: 5.0,
    date: "2025-02-10",
    title: "Игра у борта стала сильнее",
    text: "Понятные объяснения. Ребёнок стал увереннее в борьбе и единоборствах.",
    tags: ["Игровое мышление", "Подход к детям"],
    improvementArea: "Игра у борта",
    verifiedBooking: true,
  },
];
