/**
 * Dev mocks для Arena multi-observation review prototype.
 * Собраны вручную по сценариям MI/RS и типичным intent-ам.
 */

import type { ArenaReviewListItem } from "./arena-review-items-adapter-v1";

export { filterReviewItemsBySection } from "./arena-review-items-adapter-v1";

export const MOCK_ARENA_REVIEW_ITEMS: ArenaReviewListItem[] = [
  // --- SECTION A: READY TO KEEP ---
  {
    id: "mock-a-1",
    section: "READY_TO_KEEP",
    resolutionKind: "keep",
    segmentText: "Марк поздно сел в колени",
    intentKind: "create_player_observation",
    playerId: "p-mark",
    playerLabel: "Марк Голыш",
    sentiment: "negative",
    reason: "отдельное наблюдение без конфликтующих правил V1",
    order: 0,
    suggestedActionLabels: ["Подтвердить как есть"],
    segmentIndex: 0,
    originalTranscript: "Марк поздно сел в колени",
  },
  {
    id: "mock-a-2",
    section: "READY_TO_KEEP",
    resolutionKind: "keep",
    segmentText: "Гротов ошибка в зоне",
    intentKind: "create_player_observation",
    playerId: "p-grotov",
    playerLabel: "Иван Гротов",
    sentiment: "negative",
    reason: "отдельное наблюдение без конфликтующих правил V1",
    order: 1,
    suggestedActionLabels: ["Подтвердить как есть"],
    segmentIndex: 0,
    originalTranscript: "Гротов ошибка в зоне; Сидоров классно подключился",
  },
  {
    id: "mock-a-3",
    section: "READY_TO_KEEP",
    resolutionKind: "keep",
    segmentText: "Сидоров классно подключился",
    intentKind: "create_player_observation",
    playerId: "p-sidor",
    playerLabel: "Алексей Сидоров",
    sentiment: "positive",
    reason: "отдельное наблюдение без конфликтующих правил V1",
    order: 2,
    suggestedActionLabels: ["Подтвердить как есть"],
    segmentIndex: 1,
    originalTranscript: "Гротов ошибка в зоне; Сидоров классно подключился",
  },
  {
    id: "mock-a-4",
    section: "READY_TO_KEEP",
    resolutionKind: "keep",
    segmentText: "команда плохо в зоне",
    intentKind: "create_team_observation",
    playerId: null,
    playerLabel: "Команда",
    sentiment: "negative",
    reason: "отдельное наблюдение без конфликтующих правил V1",
    order: 3,
    suggestedActionLabels: ["Подтвердить как есть"],
    segmentIndex: 0,
    originalTranscript: "команда плохо в зоне; запиши это",
  },
  {
    id: "mock-a-5",
    section: "READY_TO_KEEP",
    resolutionKind: "keep",
    segmentText: "запиши это",
    intentKind: "unknown",
    playerId: null,
    playerLabel: "Без привязки",
    sentiment: "neutral",
    reason: "отдельное наблюдение без конфликтующих правил V1",
    order: 4,
    suggestedActionLabels: ["Подтвердить как есть"],
    segmentIndex: 1,
    originalTranscript: "команда плохо в зоне; запиши это",
  },
  {
    id: "mock-a-6",
    section: "READY_TO_KEEP",
    resolutionKind: "keep",
    segmentText: "запиши момент",
    intentKind: "unknown",
    playerId: null,
    playerLabel: "Без привязки",
    sentiment: "neutral",
    reason: "отдельное наблюдение без конфликтующих правил V1",
    order: 5,
    suggestedActionLabels: ["Подтвердить как есть"],
    segmentIndex: 0,
    originalTranscript: "запиши момент",
  },

  // --- SECTION B: NEEDS MERGE REVIEW ---
  {
    id: "mock-b-1",
    section: "NEEDS_MERGE_REVIEW",
    resolutionKind: "merge",
    segmentText: "Марк отлично в зоне",
    secondarySegmentText: "93-й ошибся на сине",
    intentKind: "create_player_observation",
    playerId: "p-mark",
    playerLabel: "Марк Голыш",
    sentiment: "positive",
    reason:
      "два соседних сегмента — один и тот же playerId; стабильная политика V1: merge в первый",
    sourceIndexes: [0, 1],
    mergedIntoIndex: 0,
    order: 6,
    suggestedActionLabels: ["Объединить в одно наблюдение", "Оставить как два отдельных"],
    segmentIndex: 0,
    originalTranscript: "Марк отлично в зоне, 93-й ошибся на сине",
  },
  {
    id: "mock-b-2",
    section: "NEEDS_MERGE_REVIEW",
    resolutionKind: "merge",
    segmentText: "Марк молодец",
    secondarySegmentText: "93-й ошибся",
    intentKind: "create_player_observation",
    playerId: "p-mark",
    playerLabel: "Марк Голыш",
    sentiment: "positive",
    reason:
      "два соседних сегмента — один и тот же playerId; стабильная политика V1: merge в первый",
    sourceIndexes: [0, 1],
    mergedIntoIndex: 0,
    order: 7,
    suggestedActionLabels: ["Объединить в одно наблюдение", "Оставить как два отдельных"],
    segmentIndex: 0,
    originalTranscript: "синтетический merge+keep (фрагмент)",
  },

  // --- SECTION C: NEEDS ATTENTION ---
  {
    id: "mock-c-1",
    section: "NEEDS_ATTENTION",
    resolutionKind: "ambiguous",
    segmentText: "17-й",
    intentKind: "create_player_observation",
    playerId: "p-grotov",
    playerLabel: "Иван Гротов",
    sentiment: "negative",
    reason: "транскрипт вида «N-й и M-й …» — общая оценка пары; требуется review",
    order: 8,
    suggestedActionLabels: ["Назначить игрока", "Как оценка команды", "Оставить как заметку", "Не сохранять"],
    segmentIndex: 0,
    originalTranscript: "17-й и 23-й не успели вернуться",
  },
  {
    id: "mock-c-2",
    section: "NEEDS_ATTENTION",
    resolutionKind: "ambiguous",
    segmentText: "23-й не успели вернуться",
    intentKind: "create_player_observation",
    playerId: "p-sidor",
    playerLabel: "Алексей Сидоров",
    sentiment: "negative",
    reason: "транскрипт вида «N-й и M-й …» — общая оценка пары; требуется review",
    order: 9,
    suggestedActionLabels: ["Назначить игрока", "Как оценка команды", "Оставить как заметку", "Не сохранять"],
    segmentIndex: 1,
    originalTranscript: "17-й и 23-й не успели вернуться",
  },
  {
    id: "mock-c-3",
    section: "NEEDS_ATTENTION",
    resolutionKind: "ambiguous",
    segmentText: "концовка слабая",
    intentKind: "unknown",
    playerId: null,
    playerLabel: "Без привязки",
    sentiment: "negative",
    reason:
      "продолжение team-контраста во втором сегменте (unknown); возможная одна оценка команды",
    order: 10,
    suggestedActionLabels: ["Назначить игрока", "Как оценка команды", "Оставить как заметку", "Не сохранять"],
    segmentIndex: 1,
    originalTranscript: "команда хорошо, но концовка слабая",
  },
  {
    id: "mock-c-4",
    section: "NEEDS_ATTENTION",
    resolutionKind: "ambiguous",
    segmentText: "темп просел",
    intentKind: "unknown",
    playerId: null,
    playerLabel: "Без привязки",
    sentiment: "negative",
    reason:
      "продолжение team-контраста во втором сегменте (unknown); возможная одна оценка команды",
    order: 11,
    suggestedActionLabels: ["Назначить игрока", "Как оценка команды", "Оставить как заметку", "Не сохранять"],
    segmentIndex: 1,
    originalTranscript: "команда хорошо, но темп просел",
  },
];

